package org.a4z0.lwjgl.demo.voxel.block.face;

@FunctionalInterface
public interface FaceGen {

    /**
    * ...
    *
    * @param buffer ...
    * @param x ...
    * @param y ...
    * @param z ...
    * @param r ...
    * @param g ...
    * @param b ...
    * @param a ...
    */

    void generate(DynamicBuffer buffer, float x, float y, float z, int i);
}