package org.a4z0.lwjgl.demo.voxel.block.face;

import org.a4z0.lwjgl.demo.voxel.legacy.done.buffer.DynamicBuffer;

@FunctionalInterface
public interface Face {

    /**
    * ...
    *
    * @param buffer ...
    * @param x ...
    * @param y ...
    * @param z ...
    * @param r ...
    * @param g ...
    * @param b ...
    * @param a ...
    */

    void generate(DynamicBuffer buffer, float x, float y, float z, int r, int g, int b, int a);
}