package org.a4z0.lwjgl.demo.voxel.palette;

public class Palette {

    protected final int[] e;

    /**
    * Construct a {@link Palette}.
    */

    public Palette() {
        this.e = new int[16 * 16 * 16];
    }

    /**
    * ...
    *
    * @param x ...
    * @param y ...
    * @param z ...
    * @param r ...
    * @param g ...
    * @param b ...
    */

    public void setColor(int x, int y, int z, int r, int g, int b) {
        this.setColor(x, y, z, r, g, b, 255);
    }

    /**
    * ...
    *
    * @param x ...
    * @param y ...
    * @param z ...
    * @param r ...
    * @param g ...
    * @param b ...
    * @param a ...
    */

    public void setColor(int x, int y, int z, int r, int g, int b, int a) {
        this.setColor(x, y, z, (byte) r, (byte) g, (byte) b, (byte) a);
    }

    /**
    * ...
    *
    * @param x ...
    * @param y ...
    * @param z ...
    * @param r ...
    * @param g ...
    * @param b ...
    */

    public void setColor(int x, int y, int z, byte r, byte g, byte b) {
        this.setColor(x, y, z, r, g, b, (byte) 255);
    }

    /**
    * ...
    *
    * @param x ...
    * @param y ...
    * @param z ...
    * @param r ...
    * @param g ...
    * @param b ...
    * @param a ...
    */

    public void setColor(int x, int y, int z, byte r, byte g, byte b, byte a) {
        this.setColor(x, y, z, ((a & 0xFF) << 24) | ((r & 0xFF) << 16) | ((g & 0xFF) << 8) | (b & 0xFF));
    }

    /**
    * ...
    *
    * @param x ...
    * @param y ...
    * @param z ...
    * @param i ...
    */

    public void setColor(int x, int y, int z, int i) {
        this.e[((y & 15) << 4 | (z & 15)) << 4 | (x & 15)] = i;
    }

    /**
    * ...
    *
    * @param x ...
    * @param y ...
    * @param z ...
    *
    * @return ...
    */

    public int getColor(int x, int y, int z) {
        return this.e[((y & 15) << 4 | (z & 15)) << 4 | (x & 15)];
    }
}